# Generated by Django 6.0 on 2026-01-07 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="theatrehall",
            old_name="seats_in_rows",
            new_name="seats_in_row",
        ),
    ]
