# Generated by Django 6.0 on 2026-01-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="poster",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
