# Generated by Django 6.0 on 2026-01-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "theatre",
            "0003_alter_ticket_unique_together_alter_theatrehall_rows_and_more",
        ),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="performance",
            name="unique_performance",
        ),
        migrations.AddConstraint(
            model_name="performance",
            constraint=models.UniqueConstraint(
                fields=("theatre_hall", "show_time"),
                name="unique_performance_hall_time",
            ),
        ),
        migrations.AddConstraint(
            model_name="performance",
            constraint=models.UniqueConstraint(
                fields=("play", "show_time"), name="unique_performance_play_time"
            ),
        ),
    ]
